### ISSUE TITLE
NBD Server  - Device Truncates to 1024 boundary

### ISSUE THREAD

**Issue by davidbartonau** [zbackup/zbackup#121]
The NBD server seems to truncate the input files to 1k blocks.  Is this by design?  The result is that the last block is omitted (unless it is a full block).

```
 # As an example, I generate a simple text file with 1000 lines.
OUTPUTFILE=/tmp/sample.txt

for x in `seq 1 1000`; do
    echo -n "Line $x  " >> $OUTPUTFILE
    for y in `seq 1 100`; do
        echo -n $y >> $OUTPUTFILE
    done;    
    echo >> $OUTPUTFILE
done;

 # Backup the file 
./zbackup  --non-encrypted backup /tmp/zbackup_test/backups/sample.txt < /tmp/sample.txt

 # Open an nbd
sudo ./zbackup  --non-encrypted nbd /tmp/zbackup_test/backups/sample.txt /dev/nbd0

 # Copy the device to a file (in another terminal)
sudo dd if=/dev/nbd0  of=/tmp/sample.txt.dd

wc -c /tmp/sample.txt /tmp/sample.txt.dd
202893 /tmp/sample.txt
202752 /tmp/sample.txt.dd
```

I ran the same thing, only with a 1001 line file:

```
wc -c /tmp/sample2.txt /tmp/sample.txt2.dd
203097 /tmp/sample2.txt
202752 /tmp/sample.txt2.dd
```

Notably the files are both shorter than the originals and although the originals are different lengths the versions copied from the block device are the same size.

Not understanding block devices, I am wondering if it is possible _at least_ to pad the last block with nulls.  I am updating the documentation for 1.5 release and this needs a warning on it.  That said, it's pretty amazing.  If there was an easy way to get access to this kind of data as non-root it would make using tar for these backups obsolete.

**Comment by rutsky** [comment]
@davidbartonau thanks for the detailed bug report.

This behaviour is indeed due handling of NBD as block devices.

We set NBD device size to size of unpacked data:
https://github.com/zbackup/zbackup/blob/38cee26cee4308c00497e200ca3dcd56724e6e57/zutils.cc#L295
https://github.com/zbackup/zbackup/blob/df02e1b00098b17a1ebd60b83c16b1b8eca681c9/buse.c#L115

And NBD (at least in Linux) handles sizes as `(block size, number of blocks)` pair, with default block size 1024: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/block/nbd.c#n761

```
    case NBD_SET_SIZE:
        return nbd_size_set(nbd, bdev, nbd->blksize,
                    arg / nbd->blksize);
```

this is where device size is being truncated to be multiple of 1024 size.

Though I don't think unpacking files as NBD devices is a good idea, this is a bug that should be fixed.

We indeed need to pad data to block size (block size may be configurable) and output warning if NBD served data size is not multiple of block size.

**Comment by rutsky** [comment]
@davidbartonau can you try my fix from PR #123?

**Comment by davidbartonau** [comment]
@rutsky will do.

What is a typical use for a read only block device?  It would be good to put a use case in the documentation.

**Comment by rutsky** [comment]
@davidbartonau NBD is useful when zbackup is used for storing whole disk partitions. In this case you can create virtual NBD device with virtually uncompressed/undeduplicated partition, mount file system on it (in read only mode of course), and read arbitrary files without need to restore whole partition.

When I added NBD support only this use case was in mind because disk partitions usually are really large and they _need_ to be represented in OS as block device in order to mount file system on them (on Linux).
For cases when you want to extract part of large file other tool can be implemented, [IndexedRestorer](https://github.com/zbackup/zbackup/blob/2b43de6b78594808c1a763d518770deba0c5af45/backup_restorer.hh#L68) allows to read with arbitrary offset, you just need to design and implement interface that will use it.

**Comment by davidbartonau** [comment]
@rutsky thanks for the info on the use case and pointing out the IndexedRestorer.  I wish my C++ was better, but I've been using Java for 20y and haven't touched C++ since.  I did look over the code trying to understand it.

Although that IndexedRestorer does look relatively simple to use.  Would it perform reasonably well to seek into various parts of the file and dump out the output?  I am thinking that with that class I could write a command like:

```
zbackup restore --partial <<EOF
1000,100
57000,2000
124000,3000
EOF
```

Which would then write out the corresponding 5100 bytes from the various parts of the stream cat-ed together.  Another tool can then pull out the relevant pieces and save them to the 3 files.

I wrote the program [zbackup-tar](https://github.com/davidbartonau/zbackup-tar) which has the goal of speeding up backups (primarily) but would also benefit from speeding up querying of repositories as well as restoring.  An interface like the above would give me a powerful way to selectively retrieve files.  There is nothing worse than having to restore a 9G tarfile to read a 3k file!

While I have your attention, is there a sequence of characters or pattern that triggers the creation of a deduplication boundary?  Right now, zbackup-tar spends a lot of effort trying to keep the files in a consistent order so that they are deduplicated properly.  If I could write each file and then a "flush" sequence then I could force the deduplicator to treat each file uniquely.  By removing the file headers that tar puts in between each file, the amount of deduplication could potentially increase a lot for certain use cases e.g. backing up the uat and prod versions in one backup.

**Comment by rutsky** [comment]
@davidbartonau `IndexedRestorer` should be quite fast assuming that you don't change what data is stored by zbackup. For a single backup `IndexedRestorer` loads metainformation about all stored parts of archived file (`BackupInstruction`s) in memory and then for an arbitrary position in the original file allows to find appropriate starting position between `BackupInstruction`s in O(log N) time, where N is number of `BackupInstruction`s for the backup.

So "seek" time is logarithmic of number of `BackupInstruction`s in backup, which is neglectable small time in comparison with LZMA or similar decompression time of chunks. However index for `BackupInstruction`s must be stored in memory.

Faster random seek index can be implemented if zbackup storage format will be changed, which is not worth it at this moment (IMO).

`IndexedRestorer` should be efficient enough to implement your use case of extracting parts of file with different offsets:

```
zbackup restore --partial <<EOF
1000,100
57000,2000
124000,3000
EOF
```

I'm not familiar with deduplication internals of zbackup and don't know how to eliminate deduplication issues on boundary of files in tar archive (also mentioned in #105).
IMO instead of using tar it's better to use custom format, here is one of the examples of such formats: http://duplicity.nongnu.org/new_format.html
