### ISSUE TITLE
[EXPIRED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [zbackup/zbackup#142]
Dear Konstantin,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by davidbartonau** [comment]
I'm guessing that anyone using this is a Linux / BSD / OSX user rather than a Windows user.

Maybe you should try running it in the Linux on Windows support:
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

As I understand it, you can install and run software directly within the Windows environment.  Seems really cool.

**Comment by tumagonx** [comment]
Any technical reason why? use of posix stuff?
Been looking for rsync-like backup tool in native win32 for years...

**Comment by sergeevabc** [comment]
@tumagonx, have you found any decent one to date?

**Comment by tumagonx** [comment]
@sergeevabc, nope not the free one, there is one native (very old) on SF but have issues
