### ISSUE TITLE
Cache tag standard

### ISSUE THREAD

**Issue by szepeviktor** [zbackup/zbackup#37]
Please consider implementing: http://www.brynosaurus.com/cachedir/spec.html

**Comment by brcha** [comment]
Here's what I use to backup with zbackup. I don't use tartool since tar already supports enough features to filter directories tagged by .no_backup and CACHEDIR.TAG faster:

https://gist.github.com/brcha/adb66e818e0f4dc1721a

Naturally, this is customized for my use and it first makes a btrfs snapshot of my home directory, but take a look at the tar | zbackup command. It might be interesting for you.

**Comment by Am1GO** [comment]
Cut from tar manpage:
```
[..]
       --exclude-caches
              exclude contents of directories containing CACHEDIR.TAG, except for the tag file itself

       --exclude-caches-all
              exclude directories containing CACHEDIR.TAG
[..]
```
Didn't know that before, so closing as an invalid again.
tartool will not support CACHEDIR.TAG in future.
